# Generated by Django 3.1 on 2020-10-17 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Q&A', 'Question'), ('여행 TIP', 'Tip'), ('자유 게시판', 'Post')], max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('img_path', models.FileField(blank=True, max_length=200, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.person')),
            ],
            options={
                'db_table': 'board',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.person')),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['-created'],
            },
        ),
    ]
