# Generated by Django 3.1 on 2020-10-15 08:29

import django.contrib.auth.models
from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default='email@test.com', max_length=60, unique=True)),
                ('username', models.CharField(max_length=60)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('img_profile', models.FileField(blank=True, upload_to='user')),
                ('type', models.CharField(choices=[('PERSON', 'Person'), ('ADMINUSER', 'AdminUser')], default='PERSON', max_length=10)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('member.user',),
            managers=[
                ('objects', member.models.AdminUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('member.user',),
            managers=[
                ('objects', member.models.PersonManager()),
            ],
        ),
    ]
